### ISSUE TITLE
Compatibility with Project: Save the Pets?

### ISSUE THREAD

**Issue by chocolatechipcats** [EmpressValla/TheEmeraldLasso#23]
Minecraft 1.19.2

Another mod called [Project: Save the Pets!](https://modrinth.com/mod/projectsavethepets) protects pets from getting damaged by explosions or powder snow and the like. But if I have it installed, Emerald Lasso fails. (Setting preventAttack: false doesn't work as I'd expect.) Do you have any suggestions?

Thank you!

**Comment by LJSkinner** [comment]
@chocolatechipcats 

Hi there. When you say it "fails", do you mean that it causes a crash or that attempting to pick up mobs with that mod included doesn't work?

I'm not familiar with this mod myself, but I will look into it the nearest chance I get. (probably Monday) 

I see that you've also posted on the authors Gitlab as well. I'll bookmark that as it is possible this is a mistake on my part. (This was my first mod) 

Thanks for bringing this to my attention. I appreciate it!

**Comment by chocolatechipcats** [comment]
Nothing happens. I was trying to pick up a tamed horse. Thank you.

**Comment by LJSkinner** [comment]
@chocolatechipcats 

Okay thanks! Are you playing on a server or single player? Just so I know how best to try and recreate it when I get around to testing.

Regards

**Comment by chocolatechipcats** [comment]
Singleplayer.

**Comment by LJSkinner** [comment]
@chocolatechipcats 

Thank you. I can see that it has been a while since their repo was updated (about 8 months ago in the 1.19.2 branch) and also that responses seem a bit few and far between. However, I will still do my best to see if I can figure out what's causing it to fail. I can't necessarily promise a solution but I will let you know as soon as I've looked into it. 

**Also, have you tried creating a fresh single player world, taming a horse and then trying the lasso?** If not, this would be useful for me to know as it could be that adding it to an existing world has cause some weird bug, but it's not a persistent one. If it still doesn't work then that points to it being something to do with how both mods are interacting.

Regards

**Comment by chocolatechipcats** [comment]
I made a test setup, copied these two mods (and their configs), created new world. Still happened.

For replication. configurations:

config/emeraldlasso-common.toml
```["Emerald Lasso Config"]
	#How many entities should the lasso store?
	#Range: 1 ~ 5
	num_entities_allowed = 1
	#Should the lasso have a durability? Set to false if you'd like it to take no damage
	has_durability = true
	#Do you want the lasso to pick up all entity types? Note this will bypass whatever is in the whitelists
	allow_all_entities = true
	#Do you want the lasso to use the entity health system? I.E An entity must be lowered to a certain heart threshold to be stored in the lasso
	entity_health_system = false
	#What should the minimum health threshold be for an entity to be stored in the lasso?
	#Range: 1.0 ~ 500.0
	min_entity_health = 1.5
	#Add the vanilla entities you want the lasso to pick up. Use the same pattern as the examples below.
	vanilla_entity_whitelist = ["minecraft:pig", "minecraft:bee", "minecraft:sheep", "minecraft:cow", "minecraft:wolf", "minecraft:cat", "minecraft:ocelot", "minecraft:chicken", "minecraft:villager", "minecraft:cod", "minecraft:dolphin", "minecraft:rabbit", "minecraft:polar_bear", "minecraft:squid"]
	#Same as above but for mod entities. You can put them in either, but this allows you to manage them better.
	mod_entity_whitelist = []
```

config/projectsavethepets/projectsavethepets.json
```{
  "shears": [],
  "allowDefaultShears": true,
  "revivalBlocks": [
    "minecraft:copper_block"
  ],
  "entities": {
    "allowTameableEntities": true,
    "allowFoxEntities": true,
    "allowHorseBaseEntities": true,
    "fireProofPets": true,
    "drownProofPets": true,
    "blacklistedEntities": [],
    "revivableEntities": [
      "minecraft:horse",
      "minecraft:cat",
      "doggytalents:dog"
    ],
    "reviveNamedMobs": true
  },
  "damage": {
    "preventProjectiles": false,
    "preventSwordSweep": false,
    "preventAttack": false,
    "preventExplosions": true,
    "preventHarmingPotions": true,
    "preventBerryBushDamage": true,
    "preventFreezing": true,
    "livingEffects": [
      "minecraft:instant_damage",
      "minecraft:poison"
    ],
    "undeadEffects": [
      "minecraft:instant_health",
      "minecraft:regeneration"
    ]
  }
}```

**Comment by LJSkinner** [comment]
> I made a test setup, copied these two mods (and their configs), created new world. Still happened.
> 
> For replication. configurations:
> 
> config/emeraldlasso-common.toml
> 
> ```
> 	#How many entities should the lasso store?
> 	#Range: 1 ~ 5
> 	num_entities_allowed = 1
> 	#Should the lasso have a durability? Set to false if you'd like it to take no damage
> 	has_durability = true
> 	#Do you want the lasso to pick up all entity types? Note this will bypass whatever is in the whitelists
> 	allow_all_entities = true
> 	#Do you want the lasso to use the entity health system? I.E An entity must be lowered to a certain heart threshold to be stored in the lasso
> 	entity_health_system = false
> 	#What should the minimum health threshold be for an entity to be stored in the lasso?
> 	#Range: 1.0 ~ 500.0
> 	min_entity_health = 1.5
> 	#Add the vanilla entities you want the lasso to pick up. Use the same pattern as the examples below.
> 	vanilla_entity_whitelist = ["minecraft:pig", "minecraft:bee", "minecraft:sheep", "minecraft:cow", "minecraft:wolf", "minecraft:cat", "minecraft:ocelot", "minecraft:chicken", "minecraft:villager", "minecraft:cod", "minecraft:dolphin", "minecraft:rabbit", "minecraft:polar_bear", "minecraft:squid"]
> 	#Same as above but for mod entities. You can put them in either, but this allows you to manage them better.
> 	mod_entity_whitelist = []
> ```
> 
> config/projectsavethepets/projectsavethepets.json
> 
> ```
>   "shears": [],
>   "allowDefaultShears": true,
>   "revivalBlocks": [
>     "minecraft:copper_block"
>   ],
>   "entities": {
>     "allowTameableEntities": true,
>     "allowFoxEntities": true,
>     "allowHorseBaseEntities": true,
>     "fireProofPets": true,
>     "drownProofPets": true,
>     "blacklistedEntities": [],
>     "revivableEntities": [
>       "minecraft:horse",
>       "minecraft:cat",
>       "doggytalents:dog"
>     ],
>     "reviveNamedMobs": true
>   },
>   "damage": {
>     "preventProjectiles": false,
>     "preventSwordSweep": false,
>     "preventAttack": false,
>     "preventExplosions": true,
>     "preventHarmingPotions": true,
>     "preventBerryBushDamage": true,
>     "preventFreezing": true,
>     "livingEffects": [
>       "minecraft:instant_damage",
>       "minecraft:poison"
>     ],
>     "undeadEffects": [
>       "minecraft:instant_health",
>       "minecraft:regeneration"
>     ]
>   }
> }```
> ```

Thanks for being so detailed, this will definitely help. I will try to have a look at this at some point next week, at the latest I should have an update by the end of the week.

Regards

**Comment by LJSkinner** [comment]
@chocolatechipcats 

I am little sick right now but I'll try and get to this as soon as I can.

Regards

**Comment by chocolatechipcats** [comment]
Looking forward to it!

**Comment by LJSkinner** [comment]
@chocolatechipcats 

Hi there. I know it's been a while, I've been busy with life stuff and I was waiting on the 1.19.4 mappings update. I will take this off hold once I'm done with the update. 

One thing of note is that due to the way I have structured this repo, I usually only make incremental updates to the most recent versions. So that would be 1.20.1, 1.19.4 and 1.18.2. (This is my bad as when I first made this I didn't properly account for managing different versions of the game, I'm silly sometimes lol)

However, in this particular case I am going to make an exception for 1.19.2. It may take a little bit longer than usual as I'm going to focus on getting a version of the mod out for 1.19.4 and 1.20.x first just so people have access to the mod on those versions.

Thanks again for making this issue!

Regards

**Comment by chocolatechipcats** [comment]
Thank you!

**Comment by LJSkinner** [comment]
I'm closing all issues on this repo as I'm going to archive it today. I'm moving on to other projects as I'm just not really interested in continuing it. If you want a good alternative that is regularly updated. Please check out Mob Lassos https://www.curseforge.com/minecraft/mc-mods/mob-lassos by Fuzs.
